const initialState={
    open:false,
    drawerView:'admin',
    profileDetails:false,
    openProfile: false,
    openOrganization:false,
    openSubgroup:false,
    openDM:false,
    openRequest:false,
    openScheduleMeeting:false,
    openOrganizationTab:false,
    openSubgroupTab:false,
    openDMTab:false,
    openProfileTab:false,
    openRequestTab:false,
    openAdminGroupTab:false,
    openPrivateGroupTab:false,
    openSettingTab:true,
    openSetting:false,
    openSetting:false,
    openSettingTab:true
}

const reducer = (state=initialState,action)=>{
    if(action.type==='OPEN_DRAWER'){
        return{
            ...state,
            open:true
        }
    }
    if(action.type==='CLOSE_DRAWER'){
        return{
            ...state,
            open:false
        }
    }
    if(action.type==='SELECT_DRAWER_ADMINVIEW'){
        return{
            ...state,
            drawerView:'admin'
        }
    }
    if(action.type==='SELECT_DRAWER_SETTINGVIEW'){
        return{
            ...state,
            drawerView:'setting'
        }
    }
    if(action.type==='OPEN_PROFILE_DETAILS'){
        return{
            ...state,
            profileDetails:true
        }
    }
    if(action.type==='CLOSE_PROFILE_DETAILS'){
        return{
            ...state,
            profileDetails:false
        }
    }
    if(action.type==='OPEN_PROFILE_WINDOW'){
        return{
            ...state,
            openProfile:true
        }
    }
    if(action.type==='CLOSE_PROFILE_WINDOW'){
        return{
            ...state,
            openProfile:false
        }
    }
    if(action.type==='OPEN_REQUEST_WINDOW'){
        return{
            ...state,
            openRequest:true
        }
    }
    if(action.type==='CLOSE_REQUEST_WINDOW'){
        return{
            ...state,
            openRequest:false
        }
    }
    if(action.type==='OPEN_ORGANIZATION_WINDOW'){
        return{
            ...state,
            openOrganization:true
        }
    }
    if(action.type==='CLOSE_ORGANIZATION_WINDOW'){
        return{
            ...state,
            openOrganization:false
        }
    }
    if(action.type==='OPEN_DM_WINDOW'){
        return{
            ...state,
            openDM:true
        }
    }
    if(action.type==='CLOSE_DM_WINDOW'){
        return{
            ...state,
            openDM:false
        }
    }
    if(action.type==='OPEN_SUBGROUP_WINDOW'){
        return{
            ...state,
            openSubgroup:true
        }
    }
    if(action.type==='CLOSE_SUBGROUP_WINDOW'){
        return{
            ...state,
            openSubgroup:false
        }
    }   
    if(action.type==='OPEN_SCHEDULEMEETING_WINDOW'){
        return{
            ...state,
            openScheduleMeeting:true
        }
    }
    if(action.type==='CLOSE_SCHEDULEMEETING_WINDOW'){
        return{
            ...state,
            openScheduleMeeting:false
        }
    } 
    if(action.type==='HANDLE_ORGANIZATION_TAB'){
        const currentOrganizationTab=state.openOrganizationTab
        return{
            ...state,
            openOrganizationTab:!currentOrganizationTab
        }
    }
    if(action.type==='HANDLE_SUBGROUP_TAB'){
        const currentSubgroupTab=state.openSubgroupTab
        return{
            ...state,
            openSubgroupTab:!currentSubgroupTab
        }
    }
    if(action.type==='HANDLE_DM_TAB'){
        const currentDMTAb=state.openDMTab
        return{
            ...state,
            openDMTab:!currentDMTAb
        }
    }
    if(action.type==='HANDLE_PROFILE_TAB'){
        const currentProfileTab=state.openProfileTab
        return{
            ...state,
            openProfileTab:!currentProfileTab
        }
    }
    if(action.type==='HANDLE_REQUEST_TAB'){
        const currentRequestTab=state.openRequestTab
        return{
            ...state,
            openRequestTab:!currentRequestTab
        }
    }
    if(action.type==='HANDLE_ADMINGROUP_TAB'){
        const currentAdminGroupTab=state.openAdminGroupTab
        return{
            ...state,
            openAdminGroupTab:!currentAdminGroupTab
        }
    }
    if(action.type==='HANDLE_PRIVATEGROUP_TAB'){
        const currentProfileGroupTab=state.openPrivateGroupTab
        return{
            ...state,
            openPrivateGroupTab:!currentProfileGroupTab
        }
    }
    if(action.type==='HANDLE_SETTING_TAB'){
        const currentHandleSetting=state.openSettingTab
        return{
            ...state,
            openPrivateGroupTab:!currentHandleSetting
        }
    }
    if(action.type==='OPEN_SETTING_WINDOW'){
        return{
            ...state,
            openSetting:true
        }
    }
    if(action.type==='CLOSE_SETTING_WINDOW'){
        return{
            ...state,
            openSetting:false
        }
    }
    return state
}

export default reducer